version: "3.9"

services:

  database:
    restart: always
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: products_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - database
    ports:
      - 8000:8000
    environment:
      - DB_HOST=database
      - DB_PORT=5432

  
